version: "3.3"

services:  

  eureka:
    image: eureka   
    build: ./eureka
    container_name: eureka
    ports:
      - '8761:8761'
    volumes:
      - ../logs/eureka:/opt/eureka/logs
    networks:
      - orbis

  admin:
    image: admin   
    build: ./admin
    container_name: admin
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:  
     
      - eureka
    depends_on:     
      
      - eureka     
    ports:
      - '1111:1111'
  
    networks:
      - orbis

  zuul:
    image: zuul    
    build: ./zuul
    container_name: zuul
    links:
      - eureka 
    volumes:
      - ../logs/zuul/:/opt/zuul/logs     
    ports:
      - '8079:8079'
    networks:
      - orbis

  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - ../logs/mongobingo/data:/data/db
      - ../logs/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      orbis:
        aliases:
          - mongodb

  auth:
    image: auth   
    build: ./auth
    container_name: auth
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka     
    ports:
      - '4001:4001'
    volumes:
      - ../logs/auth/:/opt/auth/logs
    networks:
      - orbis


  box:
    image: box   
    build: ./box
    container_name: box
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka     
    ports:
      - '4002:4002'
    volumes:
      - ../logs/box/:/opt/box/logs
      - ../logs/box/filestorage/:/opt/filestorage/
    networks:
      - orbis


  register:
    image: register   
    build: ./register
    container_name: register
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka     
    ports:
      - '4004:4004'
    volumes:
      - ../logs/register/logs/:/opt/register/logs
    networks:
      - orbis
      
     
      
  profile:
    image: profile   
    build: ./profile
    container_name: profile
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka     
    ports:
      - '4006:4006'
    volumes:
      - ../logs/profile/logs/:/opt/profile/logs
    networks:
      - orbis
      
  marshal:
    image: marshal   
    build: ./marshal
    container_name: marshal
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka     
    ports:
      - '4007:4007'
    volumes:
      - ../logs/marshal/logs/:/opt/marshal/logs
    networks:
      - orbis
      
  payment:
    image: payment   
    build: ./payment
    container_name: payment
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka
      - zuul     
    ports:
      - '4003:4003'
    volumes:
      - ../logs/payment/logs/:/opt/payment/logs
    networks:
      - orbis
      
  shipment:
    image: shipment   
    build: ./shipment
    container_name: shipment
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb 
      - eureka
    depends_on:     
      - mongodb
      - eureka
      - zuul   
    ports:
      - '4005:4005'
    volumes:
      - ../logs/shipment/logs/:/opt/shipment/logs
    networks:
      - orbis
      
  orbis:    
    image: orbis 
    build: ./orbis                
    container_name: orbis
    links:      
      - zuul     
    volumes:
     - ../logs/orbis/logs/:/opt/orbis/logs
    ports:
     - '9595:8080'  
    networks:
     - orbis


networks:
  orbis:
    driver: bridge
