package io.project.app.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.GeoSpatialIndexed;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@ToString
@Document(collection = "shipment")
public class Shipment implements Serializable {

    @Id
    private String id;
    @Indexed
    private String userId;
    @Indexed
    private String shipentId; //will be generated by system
    private Address shipFrom;
    private Address shipTo;
    private String equipment;//Van
    private Integer stops;
    @GeoSpatialIndexed(useGeneratedName = true)
    private List<Geo> originLocation = new ArrayList<>();
    @GeoSpatialIndexed(useGeneratedName = true)
    private List<Geo> destinationLocation = new ArrayList<>();
    private List<Address> stopLocations = new ArrayList<>();
    private Date pickupDate;
    private Date deliveryDate;
    private String shipmentType; //full or partial
    private Double rate;
    private Date recordDate;
    private String imageId;
    private Integer destinationDeadheadMiles;
    private Integer originDeadheadMiles;
    private Integer daysToPay;
    private Integer score;
    private List<Parcel> parcels = new ArrayList<>();

}
